### ISSUE TITLE
might be failing on iphones

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ep_announce#3]
I had a promise reject on iphone.  I don't have an iphone to test/fix.

**Comment by rhansen** [comment]
Do you have a stack trace?

**Comment by JohnMcLear** [comment]
Nah I got it from server logs afaik and I don't think I kept a copy.  Just disabled and moved on.  I think Dan has an apple device maybe.

**Comment by packardone** [comment]
I'll install it on our test server next week and work to get logs. I have a lot of apple devices.

**Comment by packardone** [comment]
I actually have the error. It wasn't just OS X and iOS.  Rather, we had reports and screen shots of it showing up in chrome on windows too.  It always occurred when the second person joined the session. 

An error occurred

Please press and hold Ctrl and press F5 to reload this page

If the problem persists, please send this error message to your webmaster:

ErrorId: ZfDEv5B9KSbSRhyt6mOy
Unhandled Promise rejection
URL: [removed]
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
Cannot read property 'style' of undefined
at unknown at line -1

**Comment by packardone** [comment]
![image](https://user-images.githubusercontent.com/65915306/110049596-21893e00-7d20-11eb-9c40-21063329adf5.jpeg)
