### ISSUE TITLE
Publish latest version

### ISSUE THREAD

**Issue by rhansen** [ether/ep_announce#5]
@orblivion Would you mind publishing the latest version to npm?

If you add a `NPM_TOKEN` secret to the repository settings then the GitHub publish action will automatically publish every time master is updated (see [`.github/workflows/npmpublish.yml`](https://github.com/orblivion/ep_announce/blob/3dd6227d416a72a928d22697d3b8e0969862b64f/.github/workflows/npmpublish.yml#L53-L80)).

**Comment by orblivion** [comment]
It seems to have been published. If I install it I get the latest version.
However it looks to be stuck on 0.0.3 according to the npm website at the
moment.

**Comment by orblivion** [comment]
Hmm, it's good now.

**Comment by rhansen** [comment]
Thank you!
